#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE supabase_admin LOGIN SUPERUSER PASSWORD '${POSTGRES_PASSWORD}';
    CREATE ROLE supabase_auth_admin LOGIN NOSUPERUSER CREATEDB CREATEROLE PASSWORD '${POSTGRES_PASSWORD}';
    CREATE ROLE supabase_storage_admin LOGIN NOSUPERUSER CREATEDB CREATEROLE PASSWORD '${POSTGRES_PASSWORD}';
    CREATE ROLE supabase_realtime_admin LOGIN NOSUPERUSER REPLICATION PASSWORD '${POSTGRES_PASSWORD}';

    CREATE ROLE anon NOLOGIN NOINHERIT;
    CREATE ROLE authenticated NOLOGIN NOINHERIT;
    CREATE ROLE authenticator LOGIN NOINHERIT PASSWORD '${POSTGRES_PASSWORD}';
    CREATE ROLE service_role NOLOGIN NOINHERIT BYPASSRLS;

    GRANT anon TO authenticator;
    GRANT authenticated TO authenticator;
    GRANT service_role TO authenticator;

    GRANT USAGE ON SCHEMA public TO anon;
    GRANT USAGE ON SCHEMA public TO authenticated;
    GRANT USAGE ON SCHEMA public TO service_role;

    GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
    GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO authenticated;

    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;

    CREATE EXTENSION IF NOT EXISTS pgcrypto;
EOSQL
